services:
  nginx:
    image: nginx
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - '80:80'
    depends_on:
      - server-blue
      - client

  server-blue:
    build:
      context: .
      dockerfile: server/Dockerfile
      args:
        - NODE_ENV=development
    expose:
      - '3000'
    volumes:
      - ./server:/app/server
      - ./package.json:/app/package.json
      - ./yarn.lock:/app/yarn.lock
      - ./.yarnrc.yml:/app/.yarnrc.yml
      - ./.yarn:/app/.yarn
    environment:
      - NODE_ENV=development

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
      args:
        - NODE_ENV=development
    expose:
      - '5173'
    volumes:
      - ./client:/app/client
      - ./package.json:/app/package.json
      - ./yarn.lock:/app/yarn.lock
      - ./.yarnrc.yml:/app/.yarnrc.yml
      - ./.yarn:/app/.yarn
    environment:
      - NODE_ENV=development
