version: '3.8'

networks:
  webapp:
    name: webapp

services:
  server:
    image: rdyjun/inear-server
    container_name: server
    expose:
      - '3000'
    volumes:
      - ./server:/app/server
      - ./package.json:/app/package.json
      - ./yarn.lock:/app/yarn.lock
      - ./.yarnrc.yml:/app/.yarnrc.yml
      - ./.yarn:/app/.yarn
    environment:
      - NODE_ENV=development
    networks:
      - webapp
    # healthcheck 임시 제거
    restart: unless-stopped

  client:
    image: rdyjun/inear-client
    container_name: client
    expose:
      - '5173'
    volumes:
      - ./client:/app/client
      - ./package.json:/app/package.json
      - ./yarn.lock:/app/yarn.lock
      - ./.yarnrc.yml:/app/.yarnrc.yml
      - ./.yarn:/app/.yarn
    environment:
      - NODE_ENV=development
    networks:
      - webapp
    restart: unless-stopped

  nginx:
    image: rdyjun/inear-nginx
    container_name: nginx
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    ports:
      - '80:80'
    depends_on:
      - server
      - client
    networks:
      - webapp
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: redis
    expose:
      - '6379'
    networks:
      - webapp
    restart: unless-stopped
