version: '3.8'

networks:
  webapp:
    name: webapp

services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: server
    expose:
      - '3000'
    volumes:
      - ./server:/app/server
      - ./package.json:/app/package.json
      - ./yarn.lock:/app/yarn.lock
      - ./.yarnrc.yml:/app/.yarnrc.yml
      - ./.yarn:/app/.yarn
    environment:
      - NODE_ENV=development
    networks:
      - webapp
    restart: unless-stopped

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    container_name: client
    expose:
      - '5173'
    volumes:
      - ./client:/app/client
      - ./package.json:/app/package.json
      - ./yarn.lock:/app/yarn.lock
      - ./.yarnrc.yml:/app/.yarnrc.yml
      - ./.yarn:/app/.yarn
    environment:
      - NODE_ENV=development
    networks:
      - webapp
    restart: unless-stopped

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: nginx
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    ports:
      - '80:80'
    depends_on:
      - server
    networks:
      - webapp
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: redis
    expose:
      - '6379'
    networks:
      - webapp
    restart: unless-stopped
