networks:
  webapp:
    name: webapp

services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: server
    volumes:
      - ./server:/app/server
      - ./tsconfig.json:/app/tsconfig.json
      - ./package.json:/app/package.json
      - ./yarn.lock:/app/yarn.lock
      - ./.yarnrc.yml:/app/.yarnrc.yml
      - ./.yarn:/app/.yarn
    depends_on:
      - redis
      - mysql
    command:
      - yarn
      - --cwd
      - /app/server
      - dev
    env_file:
      - ./server/.env.production
    environment:
      - NODE_ENV=production
    networks:
      - webapp
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'wget -q --spider http://server:3000/api/health || exit 1',
        ]
      interval: 7s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    container_name: client
    volumes:
      - ./client:/app/client
      - ./package.json:/app/package.json
      - ./yarn.lock:/app/yarn.lock
      - ./.yarnrc.yml:/app/.yarnrc.yml
      - ./.yarn:/app/.yarn
    environment:
      - NODE_ENV=production
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    networks:
      - webapp
    restart: unless-stopped

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: nginx
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./client/dist/:/usr/share/nginx/html
    ports:
      - '80:80'
    depends_on:
      - server
      - client
    networks:
      - webapp
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: redis
    expose:
      - '6379'
    networks:
      - webapp
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: mysql
    expose:
      - '3306'
    env_file:
      - ./server/.env.production
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - webapp
    restart: unless-stopped

volumes:
  mysql_data:
