version: '3.8'
services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "3000:3000"
    volumes:
    - ./server:/app/server
    - ./package.json:/app/package.json
    - ./yarn.lock:/app/yarn.lock
    - ./.yarnrc.yml:/app/.yarnrc.yml
    - ./.yarn:/app/.yarn

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app/client
      - ./package.json:/app/package.json
      - ./yarn.lock:/app/yarn.lock
      - ./.yarnrc.yml:/app/.yarnrc.yml
      - ./.yarn:/app/.yarn
